/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Deepak
 */
public class FStock extends javax.swing.JFrame {
//Connection cn;

    Statement st;
    public ResultSet rs = null;

    public void reset() {
        txtpID.setText(null);
        txtpName.setText(null);
        cmbpBrand.setSelectedIndex(-1);
        cmbpCat.setSelectedIndex(-1);
        txtpDesc.setText(null);
        txtpPrice.setText(null);
        txtpQun.setText(null);
        cmbpsName.setSelectedIndex(-1);
        btnUpdateUser.setEnabled(false);
        btnDeleteUser.setEnabled(false);
    }// to reset all the flieds

    public void tableDis() {
        try {
            conn cn = new conn();
            String Query = ("SELECT * FROM Stock");
            rs = cn.st.executeQuery(Query);
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }// end try catch
    }

    public void CmbSuppName() {
        try {
            conn cn3 = new conn();
            String Query = ("SELECT * FROM Supp");
            rs = cn3.st.executeQuery(Query);
            while (rs.next()) {
                cmbpsName.addItem(rs.getString("SuppFname"));
            }// end while
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }// end try multi catch
    } // comboboxSupplierName

    public void CmbCatFun() {
        try {
            conn cn3 = new conn();
            String Query = ("SELECT * FROM Cat");
            rs = cn3.st.executeQuery(Query);
            while (rs.next()) {
                cmbpCat.addItem(rs.getString("Category"));
            } // end while
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        } // end try multi catch
    } // comboboxCatogeryFunction

    public void CmbBrandFun() {
        try {
            conn cn3 = new conn();
            String Query = ("SELECT * FROM Brand");
            rs = cn3.st.executeQuery(Query);
            while (rs.next()) {
                cmbpBrand.addItem(rs.getString("BrandName"));
            } // end while
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        } //  end try multi catch
    } // comboboxBrandFunction

    /**
     * Creates new form FUsers
     */
    public FStock() {
        initComponents();
        tableDis();
        CmbSuppName();
        CmbCatFun();
        CmbBrandFun();
        btnUpdateUser.setEnabled(false);
        btnDeleteUser.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnManageCat = new javax.swing.JButton();
        btnManageBrand = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbllName6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        txtpID = new javax.swing.JTextField();
        lblfName = new javax.swing.JLabel();
        lbllName = new javax.swing.JLabel();
        txtpName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lbllName1 = new javax.swing.JLabel();
        cmbpCat = new javax.swing.JComboBox();
        lbllName2 = new javax.swing.JLabel();
        lbllName4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtpDesc = new javax.swing.JTextField();
        lbllName5 = new javax.swing.JLabel();
        cmbpBrand = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JSeparator();
        txtpQun = new javax.swing.JTextField();
        lblfName1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtpPrice = new javax.swing.JTextField();
        lblfName2 = new javax.swing.JLabel();
        lbllName8 = new javax.swing.JLabel();
        cmbpsName = new javax.swing.JComboBox();
        dcPurDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        btnAddUser.setBackground(new java.awt.Color(255, 255, 255));
        btnAddUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(0, 153, 153));
        btnAddUser.setText("Add Stock");
        btnAddUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateUser.setText("Update Stock");
        btnUpdateUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 153, 153));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(0, 153, 153));
        btnDeleteUser.setText("Delete Stock");
        btnDeleteUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnManageCat.setBackground(new java.awt.Color(255, 255, 255));
        btnManageCat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManageCat.setForeground(new java.awt.Color(0, 153, 153));
        btnManageCat.setText("Manage Category");
        btnManageCat.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnManageCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCatActionPerformed(evt);
            }
        });

        btnManageBrand.setBackground(new java.awt.Color(255, 255, 255));
        btnManageBrand.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManageBrand.setForeground(new java.awt.Color(0, 153, 153));
        btnManageBrand.setText("Manage Brand");
        btnManageBrand.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnManageBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageCat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnManageCat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lbllName6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbllName6.setForeground(new java.awt.Color(240, 240, 240));
        lbllName6.setText("Stock Info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbllName6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllName6, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblUsers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblUsers.setForeground(new java.awt.Color(0, 153, 153));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsers.setGridColor(new java.awt.Color(255, 255, 255));
        tblUsers.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        txtpID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtpID.setForeground(new java.awt.Color(0, 153, 153));
        txtpID.setBorder(null);
        txtpID.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpIDInputMethodTextChanged(evt);
            }
        });
        txtpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpIDActionPerformed(evt);
            }
        });
        txtpID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpIDKeyTyped(evt);
            }
        });

        lblfName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblfName.setForeground(new java.awt.Color(0, 153, 153));
        lblfName.setText("Product ID");

        lbllName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName.setForeground(new java.awt.Color(0, 153, 153));
        lbllName.setText("Product Name");

        txtpName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtpName.setForeground(new java.awt.Color(0, 153, 153));
        txtpName.setBorder(null);
        txtpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpNameActionPerformed(evt);
            }
        });
        txtpName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpNameKeyPressed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 153, 153));
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lbllName1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName1.setForeground(new java.awt.Color(0, 153, 153));
        lbllName1.setText("Search");

        cmbpCat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lbllName2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName2.setForeground(new java.awt.Color(0, 153, 153));
        lbllName2.setText("Product Category");

        lbllName4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName4.setForeground(new java.awt.Color(0, 153, 153));
        lbllName4.setText("Product Brand");

        txtpDesc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtpDesc.setForeground(new java.awt.Color(0, 153, 153));
        txtpDesc.setBorder(null);
        txtpDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpDescActionPerformed(evt);
            }
        });
        txtpDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpDescKeyPressed(evt);
            }
        });

        lbllName5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName5.setForeground(new java.awt.Color(0, 153, 153));
        lbllName5.setText("Product Description");

        cmbpBrand.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbpBrand.setForeground(new java.awt.Color(0, 153, 153));

        txtpQun.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtpQun.setForeground(new java.awt.Color(0, 153, 153));
        txtpQun.setBorder(null);
        txtpQun.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpQunInputMethodTextChanged(evt);
            }
        });
        txtpQun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpQunActionPerformed(evt);
            }
        });
        txtpQun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpQunKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpQunKeyTyped(evt);
            }
        });

        lblfName1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblfName1.setForeground(new java.awt.Color(0, 153, 153));
        lblfName1.setText("Product Quantity");

        txtpPrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtpPrice.setForeground(new java.awt.Color(0, 153, 153));
        txtpPrice.setBorder(null);
        txtpPrice.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpPriceInputMethodTextChanged(evt);
            }
        });
        txtpPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpPriceActionPerformed(evt);
            }
        });
        txtpPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpPriceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpPriceKeyTyped(evt);
            }
        });

        lblfName2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblfName2.setForeground(new java.awt.Color(0, 153, 153));
        lblfName2.setText("Product Price");

        lbllName8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName8.setForeground(new java.awt.Color(0, 153, 153));
        lbllName8.setText("Product Supplier");

        cmbpsName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbpsName.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblfName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(lbllName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(lbllName2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(lbllName4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(500, 500, 500)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbllName1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtpID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtpName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addComponent(cmbpCat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbllName5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblfName1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(lblfName2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtpDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(txtpQun, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(txtpPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbllName8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbpsName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbpBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbllName1)
                                .addGap(5, 5, 5)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbllName)
                                    .addComponent(lbllName2)
                                    .addComponent(lbllName4))))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtpName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbpCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbpBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllName5)
                            .addComponent(lblfName1)
                            .addComponent(lblfName2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpQun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbllName8)
                        .addGap(8, 8, 8)
                        .addComponent(cmbpsName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(dcPurDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yy-mm-dd");
            String dateobj = sdf.format(dcPurDate.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select date", "Error " + e, JOptionPane.ERROR_MESSAGE);
            return;
        } // end try catch

        //DateFormat df = new SimpleDateFormat("yy-mm-dd");
//        try{
//        if (txtpID.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product ID ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpID.requestFocus();
//           return;
//        }    
//        if (txtpName.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Name ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpName.requestFocus();
//           return;
//        }
//        if (cmbpCat.getSelectedIndex() == -1) {
//            JOptionPane.showMessageDialog(this, "Please Select Product Category ","Error",JOptionPane.ERROR_MESSAGE);
//            cmbpCat.requestFocus();
//           return;
//        }
//        if (cmbpBrand.getSelectedIndex() == -1) {
//            JOptionPane.showMessageDialog(this, "Please Select Product Brand ","Error",JOptionPane.ERROR_MESSAGE);
//            cmbpBrand.requestFocus();
//           return;
//        }
//        if (txtpDesc.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Description ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpDesc.requestFocus();
//           return;
//        }
//        if (txtpQun.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Quantity ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpQun.requestFocus();
//           return;
//        }
//        if (txtpPrice.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Price ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpPrice.requestFocus();
//           return;
//        }
//        if (cmbpsName.getSelectedIndex() == -1) {
//            JOptionPane.showMessageDialog(this, "Please Select Supplier name ","Error",JOptionPane.ERROR_MESSAGE);
//            cmbpsName.requestFocus();
//           return;
//        }
//       }catch(HeadlessException eh){}
// ============================================= to check data already exits in database ==========================================================
        try {
            conn cn2 = new conn();
            String Query = ("SELECT pID FROM Stock WHERE pID='" + txtpID.getText().toLowerCase() + "'");
            rs = cn2.st.executeQuery(Query);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Product id is already exists");
                txtpID.setText("");
                txtpID.requestFocus();
                return;
            } // end if
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        } // end try multi catch
// ====================================================== to insert data into database ================================================================
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yy-mm-dd");
            String dateobj = sdf.format(dcPurDate.getDate());
            conn cn = new conn();
            cn.st.executeUpdate("INSERT INTO Stock VALUES('" + txtpID.getText().toLowerCase() + "','" + txtpName.getText().toLowerCase() + "','" + cmbpCat.getSelectedItem().toString().toLowerCase() + "','" + cmbpBrand.getSelectedItem().toString().toLowerCase() + "','" + txtpDesc.getText().toLowerCase() + "','" + txtpQun.getText().toLowerCase().trim() + "','" + txtpPrice.getText().trim() + "','" + cmbpsName.getSelectedItem().toString().toLowerCase() + "','" + dateobj + "')");
            JOptionPane.showMessageDialog(null, "Data Inserted Successfull");
            tableDis();
            reset();
            txtpID.requestFocus();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        } // end multi try catch

//        ============================================================= this code is obsolete ==================================================
//                 if (txtpID.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product ID ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpID.requestFocus();
//           return;
//        }    
//        if (txtpName.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Name ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpName.requestFocus();
//           return;
//        }
//        if (cmbpCat.getSelectedIndex() == -1) {
//            JOptionPane.showMessageDialog(this, "Please Select Product Category ","Error",JOptionPane.ERROR_MESSAGE);
//            cmbpCat.requestFocus();
//           return;
//        }
//        if (cmbpBrand.getSelectedIndex() == -1) {
//            JOptionPane.showMessageDialog(this, "Please Select Product Brand ","Error",JOptionPane.ERROR_MESSAGE);
//            cmbpBrand.requestFocus();
//           return;
//        }
//        if (txtpDesc.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Description ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpDesc.requestFocus();
//           return;
//        }
//        if (txtpQun.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Quantity ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpQun.requestFocus();
//           return;
//        }
//        if (txtpPrice.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(this, "Please Enter Product Price ","Error",JOptionPane.ERROR_MESSAGE);
//           txtpPrice.requestFocus();
//           return;
//        }
//        if (cmbpsName.getSelectedIndex() == -1) {
//            JOptionPane.showMessageDialog(this, "Please Select Supplier name ","Error",JOptionPane.ERROR_MESSAGE);
//            cmbpsName.requestFocus();
//            return;
//        }
//   
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yy-mm-dd");
            String dateobj = sdf.format(dcPurDate.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select date", "Error " + e, JOptionPane.ERROR_MESSAGE);
            return;
        } // end try catch
        SimpleDateFormat sdf = new SimpleDateFormat("yy-mm-dd");
        String dateobj = sdf.format(dcPurDate.getDate());
        int op = JOptionPane.showConfirmDialog(null, " Are you sure want to Update ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (op == 0) {
            try {
                conn cn = new conn();
//        String sql= "update Login set(passWrd = '"+txtPassword.getText()+"',fName='"+txtfName.getText()+"',lName='"+txtlName+"'where usrName = '"+txtUsername.getText()+"')";
                String sql = "UPDATE Stock SET pName='" + txtpName.getText().toLowerCase() + "',pCat='" + cmbpCat.getSelectedItem().toString().toLowerCase() + "',pBrand='" + cmbpBrand.getSelectedItem().toString().toLowerCase() + "',pDesc='" + txtpDesc.getText().toLowerCase() + "',pQuantity='" + txtpQun.getText().trim() + "',pPrice='" + txtpPrice.getText().trim() + "',SuppFname='" + cmbpsName.getSelectedItem().toString().toLowerCase() + "',dateofpur='" + dateobj + "'where pID='" + txtpID.getText() + "' ";
                cn.st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Successfully Update");
                tableDis();
                reset();
                txtpID.requestFocus();
            } catch (SQLException sqle) {
                Logger.getLogger(FStock.class.getName()).log(Level.SEVERE, null, sqle);
            } // end try catch
        } // end if
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        reset();
        txtpID.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpIDActionPerformed
    }//GEN-LAST:event_txtpIDActionPerformed

    private void txtpIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpIDKeyPressed
    }//GEN-LAST:event_txtpIDKeyPressed

    private void txtpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpNameActionPerformed

    private void txtpNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpNameKeyPressed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int op = JOptionPane.showConfirmDialog(null, " Are you sure want to delete ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (op == 0) {
            try {
                conn cn = new conn();

                String sql = "delete from Stock where pID ='" + txtpID.getText() + "'";
                cn.st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Successfully deleted");
                tableDis();
                reset();
                txtpID.requestFocus();
            } catch (SQLException ex) {
                Logger.getLogger(FStock.class.getName()).log(Level.SEVERE, null, ex);
            } // end try catch
        } // end if 
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked

        try {
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            int selectIndex = tblUsers.getSelectedRow();
            //model.removeRow(selectIndex);
            txtpID.setText(model.getValueAt(selectIndex, 0).toString());
            txtpName.setText(model.getValueAt(selectIndex, 1).toString());
//            ======================= this part is removed from final code =================================================

            //cmbpBrand.setSelectedItem(model.getValueAt(selectIndex, 2));
            //cmbpCat.setSelectedItem(model.getValueAt(selectIndex, 3  ));
//          String cmbpB = model.getValueAt(selectIndex, 2).toString();
//          for (int i = 0; i<cmbpBrand.getItemCount();i++){
//          if (cmbpBrand.getItemAt(i).toString().equalsIgnoreCase(cmbpB)){
//          cmbpBrand.setSelectedIndex(i);
//        }
//        }
//          =============================================== to here ==========================================
            String cmbpb = (String) model.getValueAt(selectIndex, 3);
            cmbpBrand.addItem(cmbpb);
            cmbpBrand.setSelectedItem(cmbpb);
            String cmbpc = (String) model.getValueAt(selectIndex, 2);
            cmbpCat.addItem(cmbpc);
            cmbpCat.setSelectedItem(cmbpc);
//          txtconNum.setText(model.getValueAt(selectIndex, 2).toString());
//          txtpDesc.setText(model.getValueAt(selectIndex, 3).toString());
            txtpDesc.setText(model.getValueAt(selectIndex, 4).toString());
            txtpQun.setText(model.getValueAt(selectIndex, 5).toString());
            txtpPrice.setText(model.getValueAt(selectIndex, 6).toString());
            String cmbps = (String) model.getValueAt(selectIndex, 7);
            cmbpsName.addItem(cmbps);
            cmbpsName.setSelectedItem(cmbpc);
            Date date = new SimpleDateFormat("yyyy-mm-dd").parse((String) model.getValueAt(selectIndex, 8).toString());
            dcPurDate.setDate(date);
            btnUpdateUser.setEnabled(true);
            btnDeleteUser.setEnabled(true);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e);
        } // end try catch
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MaiinMenu mm = new MaiinMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {
            tableDis();
            DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
            String search = txtSearch.getText();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            tblUsers.setRowSorter(tr);
            tr.setRowFilter(javax.swing.RowFilter.regexFilter(search));
//          int row = tblUsers.getSelectedRow();
//          if(tblUsers.getRowSorter()!=null){
//          row = tblUsers.getRowSorter().convertRowIndexToModel(row);
//        }
           //tableDis();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } // end try catch
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtpIDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpIDInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpIDInputMethodTextChanged

    private void txtpDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpDescActionPerformed

    private void txtpDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpDescKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpDescKeyPressed

    private void txtpQunInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpQunInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpQunInputMethodTextChanged

    private void txtpQunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpQunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpQunActionPerformed

    private void txtpQunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpQunKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpQunKeyPressed

    private void txtpPriceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpPriceInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpPriceInputMethodTextChanged

    private void txtpPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpPriceActionPerformed

    private void txtpPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpPriceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpPriceKeyPressed

    private void txtpIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpIDKeyTyped
        char c = evt.getKeyChar();
        if ((!Character.isDigit(c))) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Please enter ProductID in Numaic value", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } // end if
        if (txtpID.getText().length() >= 6) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Mamium lengeth is 6", "Error", JOptionPane.ERROR_MESSAGE);
        } // end if 
    }//GEN-LAST:event_txtpIDKeyTyped

    private void txtpQunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpQunKeyTyped
        char c = evt.getKeyChar();
        if ((!Character.isDigit(c))) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Please enter Quantity in Numaic value", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } // end if
        if (txtpQun.getText().length() >= 10) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Mamium lengeth is 10", "Error", JOptionPane.ERROR_MESSAGE);
        } // end if
    }//GEN-LAST:event_txtpQunKeyTyped

    private void txtpPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpPriceKeyTyped
        char c = evt.getKeyChar();
        if ((!Character.isDigit(c))) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Please enter Price in Numaic value", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } // end if 
        if (txtpPrice.getText().length() >= 10) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Mamium lengeth is 10", "Error", JOptionPane.ERROR_MESSAGE);
        } // end if
    }//GEN-LAST:event_txtpPriceKeyTyped

    private void btnManageCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCatActionPerformed

        FManageCat fmcat = new FManageCat();
        fmcat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageCatActionPerformed

    private void btnManageBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBrandActionPerformed
        FManageBrand fmb = new FManageBrand();
        fmb.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnManageBrandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnManageBrand;
    private javax.swing.JButton btnManageCat;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox cmbpBrand;
    private javax.swing.JComboBox cmbpCat;
    private javax.swing.JComboBox cmbpsName;
    private com.toedter.calendar.JDateChooser dcPurDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblfName;
    private javax.swing.JLabel lblfName1;
    private javax.swing.JLabel lblfName2;
    private javax.swing.JLabel lbllName;
    private javax.swing.JLabel lbllName1;
    private javax.swing.JLabel lbllName2;
    private javax.swing.JLabel lbllName4;
    private javax.swing.JLabel lbllName5;
    private javax.swing.JLabel lbllName6;
    private javax.swing.JLabel lbllName8;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtpDesc;
    private javax.swing.JTextField txtpID;
    private javax.swing.JTextField txtpName;
    private javax.swing.JTextField txtpPrice;
    private javax.swing.JTextField txtpQun;
    // End of variables declaration//GEN-END:variables
}
