/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Deepak
 */
public class FUsers extends javax.swing.JFrame {
//Connection cn;
Statement st;

//    public Connection cn = null;
//     public Statement st = null;
//    public PreparedStatement pst = null;
   public ResultSet rs = null;
//    public String DSN = "jdbc:odbc:EmsDBDSN";
//    String Username=null,Password=null,fName=null,lName=null;
//        
    public void reset(){
        
    txtUsername.setText(null);
    txtPassword.setText(null);
    txtfName.setText(null);
    txtlName.setText(null);
    cmbGender.setSelectedIndex(-1);
    cmbUserType.setSelectedIndex(-1);
    txtconNum.setText(null);
    txtAdd.setText(null);
    btnUpdateUser.setEnabled(false);
    btnDeleteUser.setEnabled(false);
    
//    btnDeleteUser.setEnabled(false);
//    btnUpdateUser.setEnabled(false); 
    }
    public void tableDis(){
//        try {
//            Vector cnm = new Vector();
//            Vector dt = new Vector();
//            conn cn = new conn();
//            String Query = ("select * from Login");
//            rs = cn.st.executeQuery(Query);
//            ResultSetMetaData md = rs.getMetaData();
//            int c = md.getColumnCount();
//            for(int i =1;i<=c;i++){
//            cnm.addElement(md.getColumnName(i));
//            }
//            while(rs.next()){
//                Vector r = new Vector(c);
//                for(int i = 1; i<=c;i++){
//                r.addElement(rs.getObject(i));
//                }
//                dt.addElement(r);
//            }
//                    
//                    } catch (SQLException ex) {
//            Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
//        }
 


  try {
      conn cn = new conn();
            String Query = ("select * from Login");
            rs = cn.st.executeQuery(Query);
            tblUsers.setModel(DbUtils.resultSetToTableModel(rs));
       }
  catch (SQLException ex) {
  JOptionPane.showMessageDialog(null, ex);
  }
    }
 
    /**
     * Creates new form FUsers
     */
    public FUsers() {
        initComponents();
//        Username = txtUsername.getText();
//        Password = txtPassword.getText();
//        fName = txtfName.getText();
//        lName = txtlName.getText();
//        
        tableDis();
//        btnDeleteUser.setVisible(false);
//        btnClear.setVisible(false);
//        btnUpdateUser.setVisible(false);
        btnUpdateUser.setEnabled(false);
        btnDeleteUser.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbllName6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        txtfName = new javax.swing.JTextField();
        lblfName = new javax.swing.JLabel();
        lbllName = new javax.swing.JLabel();
        txtlName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lbllName1 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox();
        lbllName2 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox();
        lbllName3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtconNum = new javax.swing.JTextField();
        lbllName4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtAdd = new javax.swing.JTextField();
        lbllName5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        btnAddUser.setBackground(new java.awt.Color(255, 255, 255));
        btnAddUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(0, 153, 153));
        btnAddUser.setText("Add User");
        btnAddUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateUser.setText("Update User");
        btnUpdateUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 153, 153));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDeleteUser.setForeground(new java.awt.Color(0, 153, 153));
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lbllName6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbllName6.setForeground(new java.awt.Color(240, 240, 240));
        lbllName6.setText("            User Info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(lbllName6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllName6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblUsers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblUsers.setForeground(new java.awt.Color(0, 153, 153));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "First Name", "Last Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUsers.setGridColor(new java.awt.Color(255, 255, 255));
        tblUsers.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        txtfName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtfName.setForeground(new java.awt.Color(0, 153, 153));
        txtfName.setBorder(null);
        txtfName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtfNameInputMethodTextChanged(evt);
            }
        });
        txtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNameActionPerformed(evt);
            }
        });
        txtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfNameKeyPressed(evt);
            }
        });

        lblfName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblfName.setForeground(new java.awt.Color(0, 153, 153));
        lblfName.setText("First Name");

        lbllName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName.setForeground(new java.awt.Color(0, 153, 153));
        lbllName.setText("Last Name");

        txtlName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtlName.setForeground(new java.awt.Color(0, 153, 153));
        txtlName.setBorder(null);
        txtlName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlNameActionPerformed(evt);
            }
        });
        txtlName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlNameKeyPressed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 153, 153));
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 153, 153));
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 153, 153));
        lblPassword.setText("Password");

        txtPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 153, 153));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 153, 153));
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lbllName1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName1.setForeground(new java.awt.Color(0, 153, 153));
        lbllName1.setText("Search");

        cmbGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(0, 153, 153));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        lbllName2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName2.setForeground(new java.awt.Color(0, 153, 153));
        lbllName2.setText("Gender");

        cmbUserType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbUserType.setForeground(new java.awt.Color(0, 153, 153));
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));

        lbllName3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName3.setForeground(new java.awt.Color(0, 153, 153));
        lbllName3.setText("UserType");

        txtconNum.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtconNum.setForeground(new java.awt.Color(0, 153, 153));
        txtconNum.setBorder(null);
        txtconNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconNumActionPerformed(evt);
            }
        });
        txtconNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconNumKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconNumKeyTyped(evt);
            }
        });

        lbllName4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName4.setForeground(new java.awt.Color(0, 153, 153));
        lbllName4.setText("Contact Number");

        txtAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAdd.setForeground(new java.awt.Color(0, 153, 153));
        txtAdd.setBorder(null);
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });
        txtAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddKeyPressed(evt);
            }
        });

        lbllName5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbllName5.setForeground(new java.awt.Color(0, 153, 153));
        lbllName5.setText("Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(554, 554, 554)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllName1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(688, 688, 688)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblfName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lbllName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lbllName2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(lbllName4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtlName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtconNum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(lbllName3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(lbllName5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbllName1)
                                .addGap(5, 5, 5)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfName)
                            .addComponent(lbllName)
                            .addComponent(lbllName2)
                            .addComponent(lbllName4))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtconNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword)
                            .addComponent(lbllName3)
                            .addComponent(lbllName5))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        JOptionPane.showMessageDialog(null, "Plase Select Usertype");
        String un =txtUsername.getText().toLowerCase();
        String pw = txtPassword.getText().toLowerCase();
        String fn = txtfName.getText().toLowerCase();
        String ln = txtlName.getText().toLowerCase();
        String gen = cmbGender.getSelectedItem().toString().toLowerCase();
        String usr = cmbUserType.getSelectedItem().toString().toLowerCase();
        String cnum = txtconNum.getText().toLowerCase().trim();
        String ad = txtAdd.getText().toLowerCase();
//        try {
//            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            cn = DriverManager.getConnection("jdbc:odbc:EmsDBDSN");
//        } catch (SQLException ex) {
//            Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            st=cn.createStatement();
//        } catch (SQLException ex) {
//            Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
//        }
    try{
        if (fn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter First name","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (ln.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Last name","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
         if ((cmbGender.getSelectedIndex() == -1)){
                JOptionPane.showMessageDialog(this, "Please enter Select Gender ","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
         if (cnum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Contact Number","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
         if (un.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter User name","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
         if (pw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Password","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
          if ((cmbUserType.getSelectedIndex() == -1)){
                JOptionPane.showMessageDialog(this, "Please enter Select UserType ","Error", JOptionPane.ERROR_MESSAGE);
           return;
          }
         if (ad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
    }catch(HeadlessException eh){}
        try{
            conn cn1 = new conn();
         String Query = ("select usrName from Login where usrName='"+un+"'");
            rs = cn1.st.executeQuery(Query);   
        if(rs.next()){
        JOptionPane.showMessageDialog( this, "User name already exists");
        txtUsername.setText("");
        txtUsername.requestFocus();
         return;
   }
        }catch(HeadlessException e){} catch (SQLException e) {
    }
        
        try {
                conn cn = new conn();
            cn.st.executeUpdate("insert into Login values('"+un+"','"+pw+"','"+fn+"','"+ln+"','"+gen+"','"+usr+"','"+cnum+"','"+ad+"')");
            JOptionPane.showMessageDialog(null, "Data Inserted Successfull");
            tableDis();
            reset();
            txtfName.requestFocus();
        }catch(HeadlessException eee){} catch (SQLException eee) {
        }
//        try{
//
//            try {
//                 Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//             } catch (ClassNotFoundException ex) {
//                 Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
//             }
//            cn = DriverManager.getConnection(DSN);
//            JOptionPane.showMessageDialog(null, "1");
//            st = cn.createStatement();
//            JOptionPane.showMessageDialog(null, "2");
//
//            //String Query = "Insert into Login values Where (usrName= '"+ Username+"',passWrd='"+ Password +"',fName='" +fName+"',lNane='"+lName+"')";
//   //        String Query = "insert into Login values(null,'"+Username+"','"+Password+"','"+fName+"','"+lName+"')";
////           String un = rs.getString("usrName");
////           String pw = rs.getString("passWrd");
////           String fn = rs.getString("fName");
////           String ln = rs.getString("lName");
////           //PreparedStatement pst = cn.prepareStatement("Insert into Login values(?,?,?,?)");
////           /*PreparedStatement*/ pst = cn.prepareStatement("Insert into Login (un,pw,fn,ln)values(?,?,?,?)");
////            pst.setString(1, un);
////            pst.setString(2, pw);
////            pst.setString(3, fn);
////            pst.setString(4, ln);
////            pst.executeUpdate();
//            //String Query = "insert into Login(usrName,passwrd,fName,lName)values('" + Username + "','" +Password+ "','"+fName+"','"+lName+"')";
////             st.executeUpdate(Query);
//            //String Query = "insert into Login(usrName,passwrd,fName,lName)values(?,?,?,?)";
//            String Queryst = ("insert into Login values('"+Username+"','"+Password+"','"+fName+"',"+lName+")");
//            JOptionPane.showMessageDialog(null, "3");
//
////            pst =cn.prepareStatement(Query);
////            pst.setString(1, Username);
////            JOptionPane.showMessageDialog(null, "pst1");
////            pst.setString(2, Password);
////            JOptionPane.showMessageDialog(null, "pst2");
////            pst.setString(3, fName);
////            JOptionPane.showMessageDialog(null, "pst3");
////            pst.setString(4, lName);
////            JOptionPane.showMessageDialog(null, "pst4");
////            JOptionPane.showMessageDialog(null, "3");
////            pst.execute();
//             st.executeUpdate(Queryst);
//            JOptionPane.showMessageDialog(null, "4");
//            JOptionPane.showMessageDialog(null, "Data Inserted");
//    }catch(SQLException e){}
//
        
            
//        try{
//
//            try {
//                 Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//             } catch (ClassNotFoundException ex) {
//                 Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
//             }
//            cn = DriverManager.getConnection(DSN);
//            JOptionPane.showMessageDialog(null, "1");
//            st = cn.createStatement();
//            JOptionPane.showMessageDialog(null, "2");
//            
//            //String Query = "Insert into Login values Where (usrName= '"+ Username+"',passWrd='"+ Password +"',fName='" +fName+"',lNane='"+lName+"')";
//   //        String Query = "insert into Login values(null,'"+Username+"','"+Password+"','"+fName+"','"+lName+"')";
////           String un = rs.getString("usrName");
////           String pw = rs.getString("passWrd");
////           String fn = rs.getString("fName");
////           String ln = rs.getString("lName");
////           //PreparedStatement pst = cn.prepareStatement("Insert into Login values(?,?,?,?)");
////           /*PreparedStatement*/ pst = cn.prepareStatement("Insert into Login (un,pw,fn,ln)values(?,?,?,?)");
////            pst.setString(1, un);
////            pst.setString(2, pw);
////            pst.setString(3, fn);
////            pst.setString(4, ln);
////            pst.executeUpdate();
//            //String Query = "insert into Login(usrName,passwrd,fName,lName)values('" + Username + "','" +Password+ "','"+fName+"','"+lName+"')"; 
////             st.executeUpdate(Query);
//            //String Query = "insert into Login(usrName,passwrd,fName,lName)values(?,?,?,?)";
//            String Queryst = ("insert into Login values('"+Username+"','"+Password+"','"+fName+"',"+lName+")");
//            JOptionPane.showMessageDialog(null, "3");
//
////            pst =cn.prepareStatement(Query);
////            pst.setString(1, Username);
////            JOptionPane.showMessageDialog(null, "pst1");
////            pst.setString(2, Password);
////            JOptionPane.showMessageDialog(null, "pst2");
////            pst.setString(3, fName);
////            JOptionPane.showMessageDialog(null, "pst3");
////            pst.setString(4, lName);
////            JOptionPane.showMessageDialog(null, "pst4");
////            JOptionPane.showMessageDialog(null, "3");
////            pst.execute();
//             st.executeUpdate(Queryst);
//            JOptionPane.showMessageDialog(null, "4");
//            JOptionPane.showMessageDialog(null, "Data Inserted");
//    }catch(SQLException e){}
//    
//        } catch (SQLException ex) {
//            Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        int op = JOptionPane.showConfirmDialog(null," Are you sure want to Update ?","Confirmation",JOptionPane.YES_NO_OPTION);
     if (op==0)
     {
    try {
        conn cn = new conn();
//        String sql= "update Login set(passWrd = '"+txtPassword.getText()+"',fName='"+txtfName.getText()+"',lName='"+txtlName+"'where usrName = '"+txtUsername.getText()+"')";
    String sql= "update Login set passWrd = '"+txtPassword.getText().toLowerCase()+"',fName='"+txtfName.getText().toLowerCase()+"',lName='"+txtlName.getText().toLowerCase()+"',Gender='"+cmbGender.getSelectedItem().toString().toLowerCase()+"',UserType='"+cmbUserType.getSelectedItem().toString().toLowerCase()+"',conNum='"+txtconNum.getText()+"',Add='"+txtAdd.getText().toLowerCase()+"'where usrName = '"+txtUsername.getText().toLowerCase()+"'";
        cn.st.executeUpdate(sql);
        JOptionPane.showMessageDialog(this,"Successfully Update"); 
        tableDis();
        reset();
        txtfName.requestFocus();
    } catch (SQLException ex) {
        Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
                                                 

    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       reset();
       txtfName.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNameActionPerformed
//        // if ((txtUsername.getText().trim().length())==0)
//        if(!txtfName.getText().isEmpty())
//        {
//            //lblClear.setVisible(false);
//            //lblClear.hide();
//            lblClear.isEnabled();
//        }
//        else
//        lblClear.setVisible(false);
//        // lblClear.show();
//        //lblClear.setVisible(true);
    }//GEN-LAST:event_txtfNameActionPerformed

    private void txtfNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNameKeyPressed
//        btnDeleteUser.setVisible(true);
//        btnUpdateUser.setVisible(true);
//        if(txtfName.getText().isEmpty()){
//         btnDeleteUser.setVisible(false);
//         btnUpdateUser.setVisible(false);
//        }
    }//GEN-LAST:event_txtfNameKeyPressed

    private void txtlNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlNameActionPerformed

    private void txtlNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlNameKeyPressed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        
//        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
//             int selectedRowIndex = tblUsers.getSelectedRows();
//        model.removeRow(selectedRowIndex);
//          txtUsername.setText(model.getValueAt(selectedRowIndex, 0).toString());
//       txtPassword.setText(model.getValueAt(selectedRowIndex, 1).toString());
//       txtfName.setText(model.getValueAt(selectedRowIndex, 2).toString());
//       txtlName.setText(model.getValueAt(selectedRowIndex, 3).toString());
int op = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirmation",JOptionPane.YES_NO_OPTION);
     if (op==0)
     {
    try {
        conn cn = new conn();
       
        String sql= "delete from Login where usrName = '" + txtUsername.getText() + "'";
        cn.st.executeUpdate(sql);
        JOptionPane.showMessageDialog(this,"Successfully deleted"); 
        tableDis();
        reset();
        txtfName.requestFocus();
    } catch (SQLException ex) {
        Logger.getLogger(FUsers.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked

        // TODO add your handling code here:
//        DefaultTableModel d1 = (DefaultTableModel)tblUsers.getModel();
//        int selctIndex = tblUsers.getSelectedRow();
//        
        try{
              DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();
             int selectIndex = tblUsers.getSelectedRow();
        //model.removeRow(selectIndex);
         txtUsername.setText(model.getValueAt(selectIndex, 0).toString());
       txtPassword.setText(model.getValueAt(selectIndex, 1).toString());
       txtfName.setText(model.getValueAt(selectIndex, 2).toString());
       txtlName.setText(model.getValueAt(selectIndex, 3).toString());
//       cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String []{"Male","Female"}));
//       cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String []{"Admin","User"}));
            String cmbg =(String) model.getValueAt(selectIndex, 4);
            cmbGender.addItem(cmbg);
            cmbGender.setSelectedItem(cmbg);
            String cmbut =(String) model.getValueAt(selectIndex, 5);
            cmbUserType.addItem(cmbut);
            cmbUserType.setSelectedItem(cmbut);
        txtconNum.setText(model.getValueAt(selectIndex, 6).toString());
       txtAdd.setText(model.getValueAt(selectIndex, 7).toString());
        btnUpdateUser.setEnabled(true);
        btnDeleteUser.setEnabled(true);
        }catch(Exception ex){}
        
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        MaiinMenu mm = new MaiinMenu();
        mm.setVisible(true);
        this.dispose();                         
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
        String search = txtSearch.getText();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(model);
        tblUsers.setRowSorter(tr);
        tr.setRowFilter(javax.swing.RowFilter.regexFilter(search));
        tableDis();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtfNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtfNameInputMethodTextChanged
//        btnDeleteUser.setVisible(true);
//        btnUpdateUser.setVisible(true);
//        if(txtfName.getText().isEmpty()){
//         btnDeleteUser.setVisible(false);
//         btnUpdateUser.setVisible(false);
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNameInputMethodTextChanged

    private void txtconNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconNumActionPerformed

    private void txtconNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconNumKeyPressed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddActionPerformed

    private void txtAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddKeyPressed

    private void txtconNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconNumKeyTyped
        char c = evt.getKeyChar();
            if ((!Character.isDigit(c))) {
                  getToolkit().beep();
                  evt.consume();
                  JOptionPane.showMessageDialog(this , "Please enter Numaic value","Error", JOptionPane.ERROR_MESSAGE);
                  return;
            }
         if (txtconNum.getText().length()>=10) {
             getToolkit().beep();
             evt.consume();
             JOptionPane.showMessageDialog(this, "Mamium lengeth is 10","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtconNumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblfName;
    private javax.swing.JLabel lbllName;
    private javax.swing.JLabel lbllName1;
    private javax.swing.JLabel lbllName2;
    private javax.swing.JLabel lbllName3;
    private javax.swing.JLabel lbllName4;
    private javax.swing.JLabel lbllName5;
    private javax.swing.JLabel lbllName6;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtconNum;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtlName;
    // End of variables declaration//GEN-END:variables
}
